version: '3'
services:
  mysqldb:
    image: mysql:5.7
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=nodedb
    #volumes:
    #  - ../mysql:/var/lib/mysql            
    ports:
      - 3306:3306
  node:
    image: ircarvalho/fullnode
    container_name: node
    ports:
      - 3000:3000
    depends_on:
      - mysqldb
    command: sh -c "sleep 15 && node index.js" 
  nginx:
    depends_on:
      - node
    image: nginx:1.17.8-alpine
    container_name: myproxy
    ports:
      - 8080:80
    volumes:
      - .:/app
      - ./var/log/nginx:/var/log/nginx
      - .conf/nginx/site.conf:/etc/nginx/conf.d/default.conf



